const js = require('@eslint/js');

module.exports = [
  {
    ignores: ['node_modules/**', 'dist/**', 'coverage/**', 'libs/**', 'options/**', 'popup/**', 'blocked/**'],
  },
  {
    files: ['background/**/*.js', 'src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: {
        browser: 'readonly',
        FocusFlowState: 'readonly',
        getCurrentDateString: 'readonly',
        getDomain: 'readonly',
        getCategoryForDomain: 'readonly',
        debounce: 'readonly',
        formatTime: 'readonly',
        getCategoryColor: 'readonly',
        urlMatchesPattern: 'readonly',
        saveDataBatched: 'readonly',
        loadData: 'readonly',
        updateTrackingStateImplementation: 'readonly',
        recordTime: 'readonly',
        handleBlockingRequest: 'readonly',
        checkTimeLimitsAndRedirectIfNeeded: 'readonly',
        pruneOldData: 'readonly',
        performSave: 'readonly',
        updateRuleAndAssignmentCache: 'readonly',
        processStateUpdateQueue: 'readonly',
        sendPomodoroStatusToPopups: 'readonly',
        savePomodoroStateAndSettings: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        Date: 'readonly',
        Promise: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Math: 'readonly',
        JSON: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        console: 'readonly',
        module: 'readonly',
        extractAndNormalizeHostname: 'readonly',
        splitIntervalByHour: 'readonly',
        isScheduleActive: 'readonly',
        isProfileAllowlisted: 'readonly',
        evaluateRules: 'readonly',
        ruleMatchesUrl: 'readonly',
        domainPatternMatches: 'readonly',
        startOfPeriod: 'readonly',
        getPeriodEnd: 'readonly',
        getDateKeysBetween: 'readonly',
        migrateData: 'readonly',
        validateSchema: 'readonly',
        CURRENT_SCHEMA_VERSION: 'readonly',
        createBlockContext: 'readonly',
        storeBlockContext: 'readonly',
        createStorageManager: 'readonly',
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-prototype-builtins': 'warn',
      'no-case-declarations': 'warn',
      'prefer-const': 'warn',
      eqeqeq: ['warn', 'always'],
      'no-redeclare': 'warn',
      'no-useless-assignment': 'warn',
    },
  },
  {
    files: ['src/**/*.test.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: {
        require: 'readonly',
        describe: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      'no-undef': 'off',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-redeclare': 'off',
    },
  },
  {
    files: ['src/core/**/*.js'],
    rules: { 'no-redeclare': 'off' },
  },
  {
    files: ['scripts/**/*.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: {
        require: 'readonly',
        __dirname: 'readonly',
        process: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
];
